# Consept Deluge p2p node for distributing libfuzzerfication corpus directories

FROM debian:testing

RUN apt-get update && apt-get dist-upgrade -y && \
    apt-get install -y deluged && \
    apt-get autoremove -y && apt-get autoclean \
